### PR TITLE
Feat/localization

### PR DESCRIPTION
**Pull request by gcofficial**

### CODE REVIEW

**Comment by xerox-h20** [comment]
"Total amount" in BuySell.vue is not a variable

**Comment by xerox-h20** [comment]
Another example: SidebarQuotes.vue. The title parameter passed to Accordion is hardcoded.

**Comment by gcofficial** [comment]
> "Total amount" in BuySell.vue is not a variable
Fixed

**Comment by xerox-h20** [comment]
MainPageHeaderPairInfo.vue has not been fully localized.

**Pull request merged**
